
"""
Known ETFs available on NSE/BSE.
Updated quarterly when new ETFs launch.
"""

KNOWN_ETFS = [
    # ===================== GOLD ETFs =====================
    {
        "symbol": "GOLDBEES",
        "nse_symbol": "GOLDBEES",
        "yfinance_symbol": "GOLDBEES.NS",
        "name": "Nippon India ETF Gold BeES",
        "amc": "Nippon",
        "underlying": "gold",
        "expense_ratio": 0.82,
        "benchmark": "Domestic Gold Price",
        "launch_date": "2007-03-08",
        "is_popular": True,
    },
    {
        "symbol": "GOLDCASE",
        "nse_symbol": "GOLDCASE",
        "yfinance_symbol": "GOLDCASE.NS",
        "name": "Axis Gold ETF",
        "amc": "Axis",
        "underlying": "gold",
        "expense_ratio": 0.53,
        "benchmark": "Domestic Gold Price",
        "launch_date": "2021-11-10",
        "is_popular": False,
    },
    {
        "symbol": "HDFCGOLD",
        "nse_symbol": "HDFCGOLD",
        "yfinance_symbol": "HDFCGOLD.NS",
        "name": "HDFC Gold ETF",
        "amc": "HDFC",
        "underlying": "gold",
        "expense_ratio": 0.59,
        "benchmark": "Domestic Gold Price",
        "launch_date": "2021-12-15",
        "is_popular": True,
    },
    {
        "symbol": "SBIGETF",
        "nse_symbol": "SBIGETF",
        "yfinance_symbol": "SBIGETF.NS",
        "name": "SBI Gold ETF",
        "amc": "SBI",
        "underlying": "gold",
        "expense_ratio": 0.64,
        "benchmark": "Domestic Gold Price",
        "launch_date": "2009-04-28",
        "is_popular": True,
    },
    {
        "symbol": "ABORALGS",
        "nse_symbol": "ABORALGS",
        "yfinance_symbol": "ABORALGS.NS",
        "name": "Aditya Birla Sun Life Gold ETF",
        "amc": "ABSL",
        "underlying": "gold",
        "expense_ratio": 0.54,
        "benchmark": "Domestic Gold Price",
        "launch_date": "2011-05-27",
        "is_popular": False,
    },
    
    # ===================== SILVER ETFs =====================
    {
        "symbol": "SILVERBEES",
        "nse_symbol": "SILVERBEES",
        "yfinance_symbol": "SILVERBEES.NS",
        "name": "Nippon India Silver ETF",
        "amc": "Nippon",
        "underlying": "silver",
        "expense_ratio": 0.65,
        "benchmark": "Domestic Silver Price",
        "launch_date": "2022-01-12",
        "is_popular": True,
    },
    {
        "symbol": "SILVERETF",
        "nse_symbol": "SILVERETF",
        "yfinance_symbol": "SILVERETF.NS",
        "name": "HDFC Silver ETF",
        "amc": "HDFC",
        "underlying": "silver",
        "expense_ratio": 0.60,
        "benchmark": "Domestic Silver Price",
        "launch_date": "2022-01-18",
        "is_popular": True,
    },
    {
        "symbol": "ABORALSI",
        "nse_symbol": "ABORALSI",
        "yfinance_symbol": "ABORALSI.NS",
        "name": "Aditya Birla Sun Life Silver ETF",
        "amc": "ABSL",
        "underlying": "silver",
        "expense_ratio": 0.53,
        "benchmark": "Domestic Silver Price",
        "launch_date": "2022-01-13",
        "is_popular": False,
    },
    
    # ===================== INDEX ETFs (Nifty 50) =====================
    {
        "symbol": "NIFTYBEES",
        "nse_symbol": "NIFTYBEES",
        "yfinance_symbol": "NIFTYBEES.NS",
        "name": "Nippon India ETF Nifty BeES",
        "amc": "Nippon",
        "underlying": "nifty50",
        "expense_ratio": 0.04,
        "benchmark": "Nifty 50 TRI",
        "launch_date": "2001-12-28",
        "is_popular": True,
        "notes": "India's first ETF, most liquid",
    },
    {
        "symbol": "SETFNIF50",
        "nse_symbol": "SETFNIF50",
        "yfinance_symbol": "SETFNIF50.NS",
        "name": "SBI ETF Nifty 50",
        "amc": "SBI",
        "underlying": "nifty50",
        "expense_ratio": 0.05,
        "benchmark": "Nifty 50 TRI",
        "launch_date": "2015-07-14",
        "is_popular": True,
    },
    {
        "symbol": "ICICIB22",
        "nse_symbol": "ICICIB22",
        "yfinance_symbol": "ICICIB22.NS",
        "name": "ICICI Prudential Nifty ETF",
        "amc": "ICICI",
        "underlying": "nifty50",
        "expense_ratio": 0.05,
        "benchmark": "Nifty 50 TRI",
        "launch_date": "2013-03-20",
        "is_popular": True,
    },
    {
        "symbol": "HDFCNIFETF",
        "nse_symbol": "HDFCNIFETF",
        "yfinance_symbol": "HDFCNIFETF.NS",
        "name": "HDFC Nifty 50 ETF",
        "amc": "HDFC",
        "underlying": "nifty50",
        "expense_ratio": 0.05,
        "benchmark": "Nifty 50 TRI",
        "launch_date": "2015-12-03",
        "is_popular": True,
    },
    
    # ===================== NIFTY NEXT 50 =====================
    {
        "symbol": "JUNIORBEES",
        "nse_symbol": "JUNIORBEES",
        "yfinance_symbol": "JUNIORBEES.NS",
        "name": "Nippon India ETF Junior BeES",
        "amc": "Nippon",
        "underlying": "niftynext50",
        "expense_ratio": 0.15,
        "benchmark": "Nifty Next 50 TRI",
        "launch_date": "2003-02-21",
        "is_popular": True,
    },
    
    # ===================== BANK NIFTY =====================
    {
        "symbol": "BANKBEES",
        "nse_symbol": "BANKBEES",
        "yfinance_symbol": "BANKBEES.NS",
        "name": "Nippon India ETF Bank BeES",
        "amc": "Nippon",
        "underlying": "banknifty",
        "expense_ratio": 0.19,
        "benchmark": "Nifty Bank TRI",
        "launch_date": "2004-05-27",
        "is_popular": True,
    },
    {
        "symbol": "SETFNIFBK",
        "nse_symbol": "SETFNIFBK",
        "yfinance_symbol": "SETFNIFBK.NS",
        "name": "SBI ETF Nifty Bank",
        "amc": "SBI",
        "underlying": "banknifty",
        "expense_ratio": 0.20,
        "benchmark": "Nifty Bank TRI",
        "launch_date": "2015-07-14",
        "is_popular": True,
    },
    
    # ===================== SECTORAL ETFs =====================
    {
        "symbol": "ITBEES",
        "nse_symbol": "ITBEES",
        "yfinance_symbol": "ITBEES.NS",
        "name": "Nippon India ETF Nifty IT",
        "amc": "Nippon",
        "underlying": "niftyit",
        "expense_ratio": 0.22,
        "benchmark": "Nifty IT TRI",
        "launch_date": "2020-04-17",
        "is_popular": True,
    },
    {
        "symbol": "PSUBNKBEES",
        "nse_symbol": "PSUBNKBEES",
        "yfinance_symbol": "PSUBNKBEES.NS",
        "name": "Nippon India ETF PSU Bank BeES",
        "amc": "Nippon",
        "underlying": "psubank",
        "expense_ratio": 0.49,
        "benchmark": "Nifty PSU Bank TRI",
        "launch_date": "2007-10-25",
        "is_popular": False,
    },
    {
        "symbol": "INFRABES",
        "nse_symbol": "INFRABES",
        "yfinance_symbol": "INFRABES.NS",
        "name": "Nippon India ETF Infra BeES",
        "amc": "Nippon",
        "underlying": "infra",
        "expense_ratio": 0.49,
        "benchmark": "Nifty Infrastructure TRI",
        "launch_date": "2010-09-29",
        "is_popular": False,
    },
    {
        "symbol": "CONSUMBEES",
        "nse_symbol": "CONSUMBEES",
        "yfinance_symbol": "CONSUMBEES.NS",
        "name": "Nippon India ETF Consumption",
        "amc": "Nippon",
        "underlying": "consumption",
        "expense_ratio": 0.31,
        "benchmark": "Nifty India Consumption TRI",
        "launch_date": "2020-03-27",
        "is_popular": False,
    },
]

# Commonly recommended ETFs for passive investors
RECOMMENDED_ETFS_BY_GOAL = {
    "gold_exposure": ["GOLDBEES", "HDFCGOLD"],
    "silver_exposure": ["SILVERBEES", "SILVERETF"],
    "broad_market": ["NIFTYBEES", "SETFNIF50"],
    "large_mid_cap": ["JUNIORBEES"],
    "banking_sector": ["BANKBEES"],
}