"""add_enhanced_fields

Revision ID: 48f339bda6f1
Revises: 96e460e6067e
Create Date: 2026-02-07 00:48:55.026113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f339bda6f1'
down_revision = '96e460e6067e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
