"""add_enhanced_fields

Revision ID: 96e460e6067e
Revises: 8916343aefbe
Create Date: 2026-02-07 00:48:47.673361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e460e6067e'
down_revision = '8916343aefbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
