"""add_market_signals_table

Revision ID: b6826b7452aa
Revises: 
Create Date: 2026-03-01 18:40:22.651085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6826b7452aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_name', sa.String(length=200), nullable=True),
    sa.Column('signal_category', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('strength', sa.String(length=20), nullable=True),
    sa.Column('affected_asset_classes', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('raw_headline', sa.String(length=500), nullable=True),
    sa.Column('raw_source', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('source_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_signals_is_active'), 'market_signals', ['is_active'], unique=False)
    op.create_index(op.f('ix_market_signals_signal_category'), 'market_signals', ['signal_category'], unique=False)
    op.create_index(op.f('ix_market_signals_signal_name'), 'market_signals', ['signal_name'], unique=False)
    op.create_index('ix_signal_active_category', 'market_signals', ['is_active', 'signal_category'], unique=False)
    op.create_index('ix_signal_active_created', 'market_signals', ['is_active', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signal_active_created', table_name='market_signals')
    op.drop_index('ix_signal_active_category', table_name='market_signals')
    op.drop_index(op.f('ix_market_signals_signal_name'), table_name='market_signals')
    op.drop_index(op.f('ix_market_signals_signal_category'), table_name='market_signals')
    op.drop_index(op.f('ix_market_signals_is_active'), table_name='market_signals')
    op.drop_table('market_signals')
    # ### end Alembic commands ###
